#ifndef ErrorCode_H
#define ErrorCode_H

typedef enum{
	ERR_NO_ERROR,
	ERR_EXCEED_ALLOCATED_MEMORY,
    ERR_EXCEED_BUFFER_SIZE,
	ERR_EQUIVALENT_NODE,
    ERR_NODE_UNAVAILABLE,
    ERR_EQUIVALENT_RECORD,
    ERR_CORRUPTED_HEADER_MEMORY,
    ERR_CORRUPTED_FOOTER_MEMORY,
    ERR_FREE_NULL_PTR,
    ERR_INVALID_NEGATIVE_SIZE,
	ERR_INVALID_POOL,
	ERR_FREED_TWICE,
	ERR_INVALID_ADDRESS,
	ERR_INCORRECT_ADDRESS
}ErrorCode;

#endif // ErrorCode_H
